<?php
namespace App\Admin\Extensions\Form;

use Encore\Admin\Form\Field;

class History extends Field
{
    protected $view = 'form.history';

    public function render()
    {
        if (is_array($this->value)) {
            $this->value = json_encode($this->value, JSON_PRETTY_PRINT);
        }
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
